type Photos {
  id: Int!
  albumId: Int
  title: String
  url: String
  thumbnailUrl: String
}

type Query {
  photos(
    id: [Int]
    albumId: [Int]
    title: [String]
    url: [String]
    thumbnailUrl: [String]
  ): [Photos]
}
